package com.hbm.world;

import java.util.Random;

import com.hbm.blocks.ModBlocks;
import com.hbm.blocks.bomb.NukeMan;
import com.hbm.handler.WeightedRandomChestContentFrom1710;
import com.hbm.lib.HbmChestContents;
import com.hbm.lib.Library;

import net.minecraft.block.Block;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockLiquid;
import net.minecraft.block.material.Material;
import net.minecraft.block.state.IBlockState;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.BlockPos.MutableBlockPos;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class DesertAtom001 extends WorldGenerator
{
	Block Block2 = ModBlocks.yellow_barrel;
	Block Block3 = ModBlocks.reinforced_sand;
	Block Block4 = ModBlocks.nuke_man;
	Block Block5 = ModBlocks.deco_steel;
	Block Block6 = ModBlocks.brick_light;
	Block Block7 = ModBlocks.deco_tungsten;
	Block Block8 = ModBlocks.steel_poles;
	Block Block9 = ModBlocks.tape_recorder;
	Block Block10 = ModBlocks.machine_nuke_furnace_off;
	Block Block11 = ModBlocks.reinforced_glass;
	Block Block12 = ModBlocks.reinforced_lamp_off;
	Block Block13 = ModBlocks.pole_satellite_receiver;
	Block Block14 = ModBlocks.machine_generator;
	Block Block15 = ModBlocks.deco_titanium;
	Block Block16 = ModBlocks.block_lead;
	Block Block17 = ModBlocks.ore_schrabidium;
	Block Block18 = ModBlocks.waste_planks;
	Block Block19 = ModBlocks.machine_centrifuge;
	Block Block20 = ModBlocks.machine_uf6_tank;
	Block Block21 = ModBlocks.machine_puf6_tank;
	Block Block22 = ModBlocks.reinforced_brick;
	Block Block23 = ModBlocks.waste_earth;
	Block Block24 = ModBlocks.deco_lead;
	Block Block25 = ModBlocks.red_wire_coated;
	Block Block26 = ModBlocks.block_uranium;
	Block Block27 = ModBlocks.pole_top;
	Block Block28 = ModBlocks.machine_battery;
	Block Block29 = ModBlocks.machine_electric_furnace_off;
	
	protected Block[] GetValidSpawnBlocks()
	{
		return new Block[]
		{
			Blocks.GRASS,
			Blocks.DIRT,
			Blocks.SAND,
			Blocks.SANDSTONE,
			Blocks.STONE,
			Blocks.HARDENED_CLAY,
			Blocks.STAINED_HARDENED_CLAY,
		};
	}

	public boolean LocationIsValidSpawn(World world, BlockPos pos)
	{
		IBlockState checkBlockState = world.getBlockState(pos.down());
		Block checkBlock = checkBlockState.getBlock();
		Block blockAbove = world.getBlockState(pos).getBlock();
		Block blockBelow = world.getBlockState(pos.down(2)).getBlock();

		for (Block i : GetValidSpawnBlocks())
		{
			if (blockAbove != Blocks.AIR)
			{
				return false;
			}
			if (checkBlock == i)
			{
				return true;
			}
			else if (checkBlock == Blocks.SNOW_LAYER && blockBelow == i)
			{
				return true;
			}
			else if (checkBlockState.getMaterial() == Material.PLANTS && blockBelow == i)
			{
				return true;
			}
		}
		return false;
	}

	@Override
	public boolean generate(World world, Random rand, BlockPos pos)
	{
		return generate(world, rand, pos, false);
	}
	
	public boolean generate(World world, Random rand, BlockPos pos, boolean force)
	{
		int i = rand.nextInt(1);

		if(i == 0)
		{
		    generate_r0(world, rand, pos.getX(), pos.getY(), pos.getZ(), force);
		}

       return true;
	}

	public boolean generate_r0(World world, Random rand, int x, int y, int z, boolean force)
	{
		if(!force && !LocationIsValidSpawn(world, new BlockPos(x + 20, y, z + 16)))
		{
			return false;
		}
		MutableBlockPos pos = new BlockPos.MutableBlockPos();
		
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -5, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -5, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -5, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -5, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -5, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -5, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -5, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 20), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 20), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 20), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -5, z + 21), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -5, z + 21), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -5, z + 21), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 10), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 10), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 10), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 11), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 11), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 11), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 12), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 14), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 14), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.NORTH), 3);
		if(world.getBlockState(pos.setPos(x + 9, y + -4, z + 14)).getBlock() == Blocks.CHEST)
		{
			WeightedRandomChestContentFrom1710.generateChestContents(rand, HbmChestContents.getLoot(5), (TileEntityChest)world.getTileEntity(pos.setPos(x + 9, y + -4, z + 14)), 10);
		}
        world.setBlockState(pos.setPos(x + 10, y + -4, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 15), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 16), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 17), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 18), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 19), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 20), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 21), Blocks.WATER.getDefaultState().withProperty(BlockLiquid.LEVEL, 8), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -4, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -4, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -4, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -4, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -4, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -4, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -4, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -4, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -4, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -4, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -4, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 10), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 10), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 10), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 15), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 16), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 17), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 18), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 19), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 20), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 25), Block4.getDefaultState().withProperty(NukeMan.FACING, 2), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 14, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 15, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 1), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 1), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 2), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 2), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 14, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 15, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 3), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 14, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 15, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 4), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 5), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 5), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 5), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 5), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 5), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 6), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 6), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 6), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 6), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 7), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 7), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 7), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 7), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 8), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 8), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 8), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 8), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 8), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 8), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 8), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 8), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 8), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 9), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 9), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 9), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 9), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 9), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 10), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 10), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 10), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 10), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 10), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 10), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 10), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 10), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 11), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 11), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 11), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 11), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 11), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 11), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 12), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 12), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 12), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 12), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 12), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 12), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 13), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 13), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 13), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 13), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 13), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 13), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 14), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 14), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 14), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 14), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 14), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 14), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 15), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 15), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 15), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 15), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 15), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 16), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 16), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 16), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 16), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 16), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 17), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 17), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 17), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 17), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 17), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 18), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 18), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 18), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 18), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 18), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 19), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 19), Library.getRandomConcrete().getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 19), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 19), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 19), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 21), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 22), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 22), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 23), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 24), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 25), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 26), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 27), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 28), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 29), Blocks.WATER.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 17, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 18, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 19, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 20, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 21, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 22, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 23, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 24, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 25, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 26, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 27, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 28, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 29, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 30, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 31, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 32, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 33, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 34, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 35, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 36, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 37, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 38, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 39, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 40, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 13, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 14, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 15, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 16, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 0, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 0), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 0), Block3.getDefaultState(), 3);

		new DesertAtom002().generate_r00(world, rand, x, y, z);
		return true;

	}
}